//
//  EstimateView.swift
//  Notalyze
//
//  View and edit estimates generated by Echo
//

import SwiftUI
import MessageUI

struct EstimateView: View {
    @StateObject private var estimateGenerator = EstimateGenerator()
    @State private var estimate: VetEstimate
    @State private var showingShareSheet = false
    @State private var showingMailComposer = false
    @State private var shareText = ""
    @Environment(\.dismiss) var dismiss
    
    init(estimate: VetEstimate) {
        _estimate = State(initialValue: estimate)
    }
    
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 20) {
                    // Header
                    EstimateHeaderCard(estimate: estimate)
                    
                    // Line Items
                    EstimateItemsCard(estimate: $estimate)
                    
                    // Totals
                    EstimateTotalsCard(estimate: estimate)
                    
                    // Notes
                    EstimateNotesCard(estimate: $estimate)
                    
                    // Actions
                    VStack(spacing: 12) {
                        Button(action: {
                            shareText = estimate.formatted()
                            showingShareSheet = true
                        }) {
                            HStack {
                                Image(systemName: "square.and.arrow.up")
                                Text("Share Estimate")
                                    .font(.headline)
                            }
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .padding()
                            .background(
                                LinearGradient(
                                    colors: [.green, .mint],
                                    startPoint: .leading,
                                    endPoint: .trailing
                                )
                            )
                            .cornerRadius(12)
                        }
                        
                        Button(action: { showingMailComposer = true }) {
                            HStack {
                                Image(systemName: "envelope.fill")
                                Text("Email to Client")
                                    .font(.headline)
                            }
                            .foregroundColor(.blue)
                            .frame(maxWidth: .infinity)
                            .padding()
                            .background(Color(.systemBackground))
                            .cornerRadius(12)
                            .overlay(
                                RoundedRectangle(cornerRadius: 12)
                                    .stroke(Color.blue, lineWidth: 2)
                            )
                        }
                    }
                    .padding(.horizontal)
                }
                .padding()
            }
            .background(Color(.systemGroupedBackground))
            .navigationTitle("Estimate")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Close") {
                        dismiss()
                    }
                }
                
                ToolbarItem(placement: .navigationBarTrailing) {
                    Menu {
                        Button(action: {}) {
                            Label("Export as PDF", systemImage: "doc.fill")
                        }
                        Button(action: {}) {
                            Label("Save to Consultation", systemImage: "doc.badge.plus")
                        }
                        Divider()
                        Button(action: {}) {
                            Label("Edit Prices", systemImage: "dollarsign.circle")
                        }
                    } label: {
                        Image(systemName: "ellipsis.circle")
                    }
                }
            }
            .sheet(isPresented: $showingShareSheet) {
                if #available(iOS 16.0, *) {
                    ShareSheet(items: [shareText])
                }
            }
            .sheet(isPresented: $showingMailComposer) {
                MailComposerView(
                    recipient: "", // Would pull from contact info
                    subject: "Estimate for \(estimate.patientName)",
                    body: estimate.formatted()
                )
            }
        }
    }
}

// MARK: - Header Card

struct EstimateHeaderCard: View {
    let estimate: VetEstimate
    
    var body: some View {
        VStack(spacing: 16) {
            HStack {
                VStack(alignment: .leading, spacing: 8) {
                    Text("ESTIMATE")
                        .font(.caption)
                        .fontWeight(.bold)
                        .foregroundColor(.secondary)
                    
                    Text(estimate.clientName)
                        .font(.title2.bold())
                    
                    HStack(spacing: 8) {
                        Image(systemName: "pawprint.fill")
                            .font(.caption)
                            .foregroundColor(.green)
                        Text(estimate.patientName)
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                    }
                }
                
                Spacer()
                
                VStack(alignment: .trailing, spacing: 4) {
                    StatusBadge(status: estimate.status)
                    
                    Text(estimate.date.formatted(date: .abbreviated, time: .omitted))
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
        }
        .padding()
        .background(Color(.systemBackground))
        .cornerRadius(12)
        .shadow(color: Color.black.opacity(0.05), radius: 8)
    }
}

struct StatusBadge: View {
    let status: EstimateStatus
    
    var color: Color {
        switch status {
        case .draft: return .orange
        case .sent: return .blue
        case .approved: return .green
        case .invoiced: return .purple
        }
    }
    
    var body: some View {
        Text(status.rawValue)
            .font(.caption.bold())
            .foregroundColor(color)
            .padding(.horizontal, 10)
            .padding(.vertical, 4)
            .background(color.opacity(0.15))
            .cornerRadius(6)
    }
}

// MARK: - Items Card

struct EstimateItemsCard: View {
    @Binding var estimate: VetEstimate
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text("Services")
                    .font(.headline)
                Spacer()
                Text("\(estimate.items.count) items")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Divider()
            
            ForEach(estimate.items) { item in
                EstimateLineItemRow(item: item)
                
                if item.id != estimate.items.last?.id {
                    Divider()
                }
            }
        }
        .padding()
        .background(Color(.systemBackground))
        .cornerRadius(12)
        .shadow(color: Color.black.opacity(0.05), radius: 8)
    }
}

struct EstimateLineItemRow: View {
    let item: EstimateLineItem
    
    var body: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 4) {
                Text(item.procedure.name)
                    .font(.system(size: 15))
                
                Text(item.procedure.category.rawValue)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Spacer()
            
            VStack(alignment: .trailing, spacing: 4) {
                Text("x\(item.quantity)")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                Text("$\(String(format: "%.2f", item.total))")
                    .font(.system(size: 15, weight: .semibold))
            }
        }
    }
}

// MARK: - Totals Card

struct EstimateTotalsCard: View {
    let estimate: VetEstimate
    
    var body: some View {
        VStack(spacing: 12) {
            HStack {
                Text("Subtotal")
                    .font(.subheadline)
                Spacer()
                Text("$\(String(format: "%.2f", estimate.subtotal))")
                    .font(.subheadline)
            }
            
            if estimate.tax > 0 {
                HStack {
                    Text("Tax")
                        .font(.subheadline)
                    Spacer()
                    Text("$\(String(format: "%.2f", estimate.tax))")
                        .font(.subheadline)
                }
            }
            
            Divider()
            
            HStack {
                Text("Total")
                    .font(.title3.bold())
                Spacer()
                Text("$\(String(format: "%.2f", estimate.total))")
                    .font(.title3.bold())
                    .foregroundColor(.green)
            }
        }
        .padding()
        .background(Color(.systemBackground))
        .cornerRadius(12)
        .shadow(color: Color.black.opacity(0.05), radius: 8)
    }
}

// MARK: - Notes Card

struct EstimateNotesCard: View {
    @Binding var estimate: VetEstimate
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Notes")
                .font(.headline)
            
            TextEditor(text: $estimate.notes)
                .frame(height: 100)
                .padding(8)
                .background(Color(.systemGray6))
                .cornerRadius(8)
        }
        .padding()
        .background(Color(.systemBackground))
        .cornerRadius(12)
        .shadow(color: Color.black.opacity(0.05), radius: 8)
    }
}

// MARK: - Share Sheet

struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]
    
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    
    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}

// MARK: - Mail Composer

struct MailComposerView: UIViewControllerRepresentable {
    let recipient: String
    let subject: String
    let body: String
    @Environment(\.dismiss) var dismiss
    
    func makeUIViewController(context: Context) -> MFMailComposeViewController {
        let composer = MFMailComposeViewController()
        composer.setToRecipients([recipient])
        composer.setSubject(subject)
        composer.setMessageBody(body, isHTML: false)
        composer.mailComposeDelegate = context.coordinator
        return composer
    }
    
    func updateUIViewController(_ uiViewController: MFMailComposeViewController, context: Context) {}
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, MFMailComposeViewControllerDelegate {
        let parent: MailComposerView
        
        init(_ parent: MailComposerView) {
            self.parent = parent
        }
        
        func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
            parent.dismiss()
        }
    }
}

#Preview {
    EstimateView(estimate: VetEstimate(
        id: UUID(),
        clientName: "Joe Robinson",
        patientName: "Thunder",
        date: Date(),
        items: [
            EstimateLineItem(
                procedure: ProcedureItem(name: "Emergency Farm Call", price: 150.00, category: .visit),
                quantity: 1
            ),
            EstimateLineItem(
                procedure: ProcedureItem(name: "Colic Examination", price: 150.00, category: .examination),
                quantity: 1
            ),
            EstimateLineItem(
                procedure: ProcedureItem(name: "Nasogastric Intubation", price: 65.00, category: .treatment),
                quantity: 1
            )
        ],
        notes: "Based on consultation discussion",
        status: .draft
    ))
}
